import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { packageVersions } from "../../package-versions";
import { readTemplate } from "../../template-engine";
import type { PackageMap, ProjectOptions } from "../../types";
import { generateDbPassword, generateJwtSecret } from "../shared/files";
import { resolveDockerCompose } from "../shared/runtime";

export async function generateNextJsProject(options: ProjectOptions) {
  const targetDir = join(process.cwd(), options.projectName);
  const dbPassword = generateDbPassword();

  console.log(`\n🚀 Scaffolding Next.js App Router...`);

  await mkdir(join(targetDir, "app"), { recursive: true });

  const nextDependencies: PackageMap = {
    "@prisma/adapter-pg": packageVersions.dependencies["@prisma/adapter-pg"],
    "@prisma/client": packageVersions.dependencies["@prisma/client"],
    next: "^16.2.10",
    pg: packageVersions.dependencies.pg,
    react: "^19.2.7",
    "react-dom": "^19.2.7",
  };
  const nextDevDependencies: PackageMap = {
    "@prisma/config": packageVersions.devDependencies["@prisma/config"],
    "@types/node": packageVersions.devDependencies["@types/node"],
    "@types/pg": packageVersions.devDependencies["@types/pg"],
    "@types/react": "^19.2.17",
    "@types/react-dom": "^19.2.3",
    eslint: "^9.0.0",
    "eslint-config-next": "^16.2.10",
    prisma: packageVersions.devDependencies.prisma,
    typescript: packageVersions.devDependencies.typescript,
  };
  if (options.authTarget === "local") {
    nextDependencies.zod = "^3.23.0";
    nextDependencies.bcryptjs = "^2.4.3";
    nextDependencies.jsonwebtoken = packageVersions.dependencies.jsonwebtoken;
    nextDevDependencies["@types/jsonwebtoken"] = packageVersions.devDependencies["@types/jsonwebtoken"];
    nextDevDependencies["@types/bcryptjs"] = "^2.4.6";
  } else if (options.authTarget === "supabase") {
    nextDependencies.zod = "^3.23.0";
    nextDependencies["@supabase/supabase-js"] = "^2.43.0";
  } else if (options.authTarget === "clerk") {
    nextDependencies["@clerk/nextjs"] = "^7.0.0";
  }

  if (options.cachingTarget === "docker") {
    nextDependencies.ioredis = "^5.4.1";
  } else if (options.cachingTarget === "upstash") {
    nextDependencies["@upstash/redis"] = "^1.31.5";
  }

  const pkgJson = {
    name: options.projectName.split("/").pop() || "nextjs-app",
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      test: "bun test",
      postinstall: "prisma generate",
      "db:generate": "bunx --bun prisma generate",
      "db:push": "bunx --bun prisma db push",
      "db:studio": "bunx --bun prisma studio",
    },
    dependencies: nextDependencies,
    devDependencies: nextDevDependencies,
  };

  console.log(
    `\n🔒 Configuring Security Headers (Helmet & CORS) & Database...`,
  );

  const envPath = join(targetDir, ".env");
  let envContent = "";
  if (options.dbTarget === "supabase") {
    const parsed = new URL(options.supabaseDbUrl || "postgresql://postgres:postgres@aws-0-eu-central-1.pooler.supabase.com:5432/postgres");
    envContent = `DATABASE_URL="${options.supabaseDbUrl}"\nDIRECT_URL="postgresql://${parsed.username}:${parsed.password}@${parsed.hostname}:5432/postgres"\nJWT_SECRET="${generateJwtSecret()}"\n`;
  } else {
    const port = options.dbTarget === "docker" ? (options.dbPort ?? 54320).toString() : "5432";
    const pass = options.dbTarget === "docker" ? dbPassword : "postgres";
    const dbName = options.projectName.replace(/[\\/]/g, "-");
    envContent = `DATABASE_URL="postgresql://postgres:${pass}@localhost:${port}/${dbName}?schema=public"\nJWT_SECRET="${generateJwtSecret()}"\n`;
  }
  if (options.authTarget === "clerk") {
    envContent += `\n# Clerk Auth\nNEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="YOUR_CLERK_PUBLISHABLE_KEY"\nCLERK_SECRET_KEY="YOUR_CLERK_SECRET_KEY"\n`;
  } else if (options.authTarget === "supabase") {
    envContent += `\n# Supabase Auth\nNEXT_PUBLIC_SUPABASE_URL="https://your-project.supabase.co"\nNEXT_PUBLIC_SUPABASE_ANON_KEY="your-anon-key"\n`;
  }
  await Bun.write(envPath, envContent);

  const prismaClientStub = options.dbTarget === "supabase"
    ? await readTemplate("express/prisma-client.supabase.ts")
    : await readTemplate("express/prisma-client.default.ts");

  const files: Array<[string, string | undefined]> = [
    ["package.json", JSON.stringify(pkgJson, null, 2)],
    ["next-env.d.ts", "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// This file is generated by Next.js. Do not edit it directly.\n"],
    ["next.config.mjs", await readTemplate("nextjs/next.config.mjs")],
    ["tsconfig.json", JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", ".next/dev/types/**/*.ts"],
      exclude: ["node_modules"],
    }, null, 2)],
    ["app/layout.tsx", "import type { ReactNode } from \"react\";\nimport \"./globals.css\";\n\nexport const metadata = {\n  title: \"Qwykz Next App\",\n  description: \"Generated by qwykz\",\n};\n\nexport default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n"],
    ["app/globals.css", ":root {\n  color-scheme: light;\n}\n\n* {\n  box-sizing: border-box;\n}\n\nbody {\n  margin: 0;\n  background: #f8fafc;\n  color: #111827;\n  font-family: Arial, Helvetica, sans-serif;\n}\n\nbutton,\ninput {\n  font: inherit;\n}\n"],
    ["prisma/schema.prisma", await readTemplate("express/schema.prisma")],
    ["prisma.config.ts", await readTemplate("express/prisma.config.ts")],
    ["lib/prisma.ts", prismaClientStub],
    ["app/api/health/route.ts", await readTemplate("nextjs/health.route.ts")],
    ["__tests__/example.test.ts", await readTemplate("nextjs/example.test.ts.stub")],
  ];

  if (options.authTarget === "local") {
    files.push(["app/api/auth/register/route.ts", await readTemplate("nextjs/auth.route.ts")]);
    files.push(["app/api/auth/login/route.ts", await readTemplate("nextjs/login.route.ts")]);
  }

  if (options.authTarget === "clerk") {
    files.push(["middleware.ts", await readTemplate("nextjs/clerk-middleware.ts.stub")]);
    files.push(["app/page.tsx", await readTemplate("nextjs/page.clerk.tsx.stub")]);
  } else if (options.authTarget === "supabase") {
    files.push(["app/page.tsx", await readTemplate("nextjs/page.supabase.tsx.stub")]);
    const supabaseClient = await readTemplate("react/supabase.ts.stub");
    files.push(["lib/supabase.ts", supabaseClient.replace(/import\.meta\.env\.VITE/g, "process.env.NEXT_PUBLIC")]);
    files.push(["lib/AuthContext.tsx", await readTemplate("react/AuthContext.tsx.stub")]);
  } else {
    files.push(["app/page.tsx", await readTemplate("nextjs/page.local.tsx.stub")]);
  }

  if (options.dbTarget === "docker" || options.cachingTarget === "docker") {
    files.push(["docker-compose.yml", await resolveDockerCompose(options.projectName, dbPassword, options.dbTarget, options.cachingTarget, options.dbPort, options.redisPort)]);
  }

  if (options.cachingTarget === "docker") {
    files.push(["lib/redis.ts", await readTemplate("express/redis.docker.ts")]);
  } else if (options.cachingTarget === "upstash") {
    files.push(["lib/redis.ts", await readTemplate("express/redis.upstash.ts")]);
  }

  await Promise.all(
    files.map(async ([path, content]) => {
      const fullPath = join(targetDir, path);
      await mkdir(dirname(fullPath), { recursive: true });
      await Bun.write(fullPath, content || "");
    })
  );

  if (options.authTarget === "clerk") {
    const layoutPath = join(targetDir, "app", "layout.tsx");
    let layoutContent = await Bun.file(layoutPath).text();
    layoutContent = layoutContent.replace(
      "import \"./globals.css\";",
      "import \"./globals.css\";\nimport { ClerkProvider } from \"@clerk/nextjs\";"
    );
    layoutContent = layoutContent.replace(
      "<body>{children}</body>",
      "<body><ClerkProvider>{children}</ClerkProvider></body>"
    );
    await Bun.write(layoutPath, layoutContent);
  }

}
