#!/usr/bin/env bun
import { CAPABILITY_MATRIX } from "../src/capability/matrix";
import type { CapabilityStatus } from "../src/capability/types";

const ICON: Record<CapabilityStatus, string> = {
  supported: "✅",
  experimental: "🧪",
  planned: "🗓",
  unsupported: "—",
};

function renderTargets(targets: Record<string, CapabilityStatus>): string {
  return Object.entries(targets)
    .map(([name, status]) => `${ICON[status]} ${name}`)
    .join("<br>");
}

const rows = Object.entries(CAPABILITY_MATRIX.matrix).map(([framework, capabilities]) =>
  `| ${framework} | ${renderTargets(capabilities.dbTargets)} | ${renderTargets(capabilities.authTargets)} | ${renderTargets(capabilities.cachingTargets)} | ${capabilities.dockerfile ? "✅" : "—"} |`,
);

const markdown = `# qwykz Capability Matrix

> Generated by \`bun run capabilities:generate\`. Do not edit this file manually.

Legend: ✅ supported · 🧪 experimental (requires \`--experimental\`) · 🗓 planned · — unsupported/not applicable

| Framework | Database targets | Authentication targets | Cache targets | Dockerfile |
|---|---|---|---|:---:|
${rows.join("\n")}

Unsupported and planned combinations are rejected before project files are written.
`;

await Bun.write("docs/capability-matrix.md", markdown);
await Bun.write("capability-matrix.json", `${JSON.stringify(CAPABILITY_MATRIX, null, 2)}\n`);
console.log("Generated docs/capability-matrix.md and capability-matrix.json");
