import type { ProjectOptions, ScaffoldPlan } from "../types";
import { getFrameworkLearnProfile } from "./stacks";

export function generateHandsOnGuide(
  input: ProjectOptions | ScaffoldPlan,
): string {
  const options: ProjectOptions = "options" in input ? input.options : input;
  const profile = getFrameworkLearnProfile(options);

  const isDockerDb = options.dbTarget === "docker";
  const installCmd =
    profile.category === "node" || profile.category === "web" || profile.category === "fullstack"
      ? "bun install"
      : options.framework === "go"
        ? "go mod tidy"
        : options.framework === "rust"
          ? "cargo build"
          : options.framework === "laravel"
            ? "composer install"
            : "pip install -r requirements.txt";

  const devCmd =
    options.framework === "laravel"
      ? "php artisan serve"
      : options.framework === "go"
        ? "go run cmd/api/main.go"
        : options.framework === "rust"
          ? "cargo run"
          : options.framework === "python"
            ? "venv/bin/uvicorn app.main:app --reload"
            : "bun run dev";

  const milestonesRendered = profile.milestones
    .map((m) => {
      const methodsList = m.keyMethods
        .map((km) => `- \`${km.name}\`: ${km.purpose}`)
        .join("\n");

      return `### Milestone ${m.number}: ${m.title}

#### 🎯 Goal
${m.goal}

#### 💡 Concept & Best Practice
${m.concept}

> **Best Practice**: ${m.bestPractice}

#### 🛠️ Key Methods & APIs to Use
${methodsList}

#### ✅ Verification Command
Run this command in your terminal to verify your implementation:
\`\`\`bash
${m.verificationCommand}
\`\`\`
`;
    })
    .join("\n---\n\n");

  return `# Hands-On Developer Guide: Build ${options.projectName} from Scratch

> Generated by [qwykz](https://github.com/MarcZxc1/qwykz) in **--learn** mode.
>
> **Philosophy**: You learn best by building with your own hands.
> This workspace contains your project directory skeleton, tooling configurations, and dependency manifests,
> but **no finished application boilerplate**.
>
> **Not spoon-feeding**: This guide does not paste finished applications for you to mindlessly copy.
> Instead, each milestone is explained in **clear English**, establishes **architectural best practices**,
> and highlights the **exact methods and APIs** you need to implement each feature yourself.

---

## Stack Blueprint

- **Framework** : ${profile.name} (\`${options.framework}\`)
- **Database**  : ${options.dbTarget}
- **Auth**      : ${options.authTarget}
- **Caching**   : ${options.cachingTarget}
- **Entry File**: \`${profile.entryPoint}\`

---

## How to Work Through This Guide

1. **Keep this file open** in a split pane in your code editor.
2. Complete each milestone in sequence — each builds upon the previous layer.
3. Use the provided **Key Methods & APIs to Use** to construct your code.
4. Run the **Verification Command** to prove that your code works before moving to the next milestone.

---

## The Feature Milestones

${milestonesRendered}

---

## Architectural Request Lifecycle Reference

When your application is fully implemented, this is how requests flow through your software:

\`\`\`
${profile.requestFlowAscii.trim()}
\`\`\`

---
*Built with qwykz — empowering developers to master their stack through deliberate practice.*
`;
}
