import type { ProjectOptions, ScaffoldPlan } from "../types";
import { getFrameworkLearnProfile } from "./stacks";

export function generateLearnGuide(
  input: ProjectOptions | ScaffoldPlan,
): string {
  const options: ProjectOptions = "options" in input ? input.options : input;
  const profile = getFrameworkLearnProfile(options);

  const isDockerDb = options.dbTarget === "docker";
  const installCmd =
    profile.category === "node" || profile.category === "web" || profile.category === "fullstack"
      ? "bun install"
      : options.framework === "go"
        ? "go mod tidy"
        : options.framework === "rust"
          ? "cargo build"
          : options.framework === "laravel"
            ? "composer install"
            : "pip install -r requirements.txt";

  const devCmd =
    options.framework === "laravel"
      ? "php artisan serve"
      : options.framework === "go"
        ? "go run cmd/api/main.go"
        : options.framework === "rust"
          ? "cargo run"
          : options.framework === "python"
            ? "venv/bin/uvicorn app.main:app --reload"
            : "bun run dev";

  const dbSetupCmd =
    options.framework === "laravel"
      ? "php artisan migrate"
      : options.framework === "go"
        ? "Auto-migrated by GORM on startup"
        : options.framework === "rust"
          ? "sqlx migrate run"
          : options.framework === "python"
            ? "Auto-migrated on startup or via alembic"
            : profile.category === "web"
              ? "N/A (Frontend SPA connects to backend API)"
              : "bun run db:push";

  const healthPort = options.framework === "rust" || options.framework === "go" ? "8080" : "3000";

  const keyFilesRows = profile.keyFiles
    .map((kf) => `| \`${kf.path}\` | ${kf.role} |`)
    .join("\n");

  const frameworkMethodsList = profile.frameworkMethods
    .map(
      (m) =>
        `#### \`${m.name}\`\n${m.signature ? `- **Signature**: \`${m.signature}\`\n` : ""}- **Purpose**: ${m.purpose}\n`,
    )
    .join("\n");

  const ormMethodsList = (profile.ormMethods ?? [])
    .map(
      (m) =>
        `#### \`${m.name}\`\n${m.signature ? `- **Signature**: \`${m.signature}\`\n` : ""}- **Purpose**: ${m.purpose}\n`,
    )
    .join("\n");

  const authMethodsList = (profile.authMethods ?? [])
    .map(
      (m) =>
        `#### \`${m.name}\`\n${m.signature ? `- **Signature**: \`${m.signature}\`\n` : ""}- **Purpose**: ${m.purpose}\n`,
    )
    .join("\n");

  return `# Architecture & Codebase Guide: ${options.projectName}

> Generated by [qwykz](https://github.com/MarcZxc1/qwykz).
> This companion guide explains the generated boilerplate: the primary starting point, how to make it functional,
> the internal request flow, and the syntax & framework methods used across the codebase.

---

## 1. The Starting Point (Where Execution Begins)

- **Primary Entry File**: \`${profile.entryPoint}\`
- **Application Bootstrap**:
  ${profile.bootstrapExplanation}

### Key Files & Their Architectural Roles

| File Path | Role |
| :--- | :--- |
${keyFilesRows}

---

## 2. How to Make It Functional (Setup & Run)

Follow these steps to initialize and start your project:

1. **Install Dependencies**:
   \`\`\`bash
   ${installCmd}
   \`\`\`

2. **Configure Environment Variables**:
   Copy \`.env.example\` to \`.env\` and inspect configured ports and secrets.
   \`\`\`bash
   cp .env.example .env
   \`\`\`

3. **Database Setup & Migrations**:
   ${isDockerDb ? "Start your Docker PostgreSQL container first:\n   ```bash\n   docker compose up -d\n   ```\n   Then synchronize your schema:\n" : "Synchronize your schema:\n"}   \`\`\`bash
   ${dbSetupCmd}
   \`\`\`

4. **Start the Development Server**:
   \`\`\`bash
   ${devCmd}
   \`\`\`

5. **Verify the Health Check**:
   \`\`\`bash
   curl -i http://localhost:${healthPort}/api/health
   \`\`\`

---

## 3. Request Flow & Mental Model

How an incoming HTTP request travels through the layers of this generated architecture:

\`\`\`
${profile.requestFlowAscii.trim()}
\`\`\`

---

## 4. Syntax & Methods Reference

This section details the framework methods, ORM queries, and auth functions implemented in your codebase.

### Framework Methods (${profile.name})

${frameworkMethodsList}

${profile.ormMethods && profile.ormMethods.length > 0 ? `### Database & ORM Methods\n\n${ormMethodsList}\n` : ""}
${profile.authMethods && profile.authMethods.length > 0 ? `### Authentication & Security Methods\n\n${authMethodsList}\n` : ""}

---

## 5. How to Extend This Codebase

### Adding a New Route
${profile.extensionGuide.addRoute}

### Adding a Database Model & Running Migrations
${profile.extensionGuide.addModel}

### Protecting an Endpoint with Auth
${profile.extensionGuide.protectRoute}

---
*Built with qwykz — deterministic, inspectable, and honest project scaffolding.*
`;
}
